name: workflow_plan


on:
    push:
        branches:
            - dev
            - qa
            - main

jobs:
    all-workflow-terraform-plan:
        strategy:
            matrix:
                environment: [dev, qa, prd]
        name: Terraform Plan for ${{ matrix.environment }}
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
          - name: Setup Terraform
            uses: hashicorp/setup-terraform@v1
            with: 
              terraform_version: 1.7.0
          - name: Terraform Plan
            run: |
              terraform init -backend-config=envs/${{ matrix.environment }}.backend.conf
              terraform plan -var-file=envs/${{ matrix.environment }}.tfvars

            working-directory: terraform
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        