name: workflow_deploy

on: 
    workflow_dispatch:
    push:
        branches:
            - dev
            - qa
            - main

jobs:
    terraform-deploy-dev:
        name: Terraform Deploy for dev
        if: github.ref == 'refs/heads/dev' # Only run this job on the dev branch
        runs-on: ubuntu-latest
        steps:
          - name: Terraform Apply
            run: terraform apply -auto-approve -var-file=envs/dev.tfvars
            working-directory: terraform
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    terraform-deploy-qa:
        name: Terraform Deploy for qa
        if: github.ref == 'refs/heads/qa' # Only run this job on the qa branch
        runs-on: ubuntu-latest
        steps:
          - name: Terraform Apply
            run: terraform apply -auto-approve -var-file=envs/qa.tfvars
            working-directory: terraform
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    terraform-deploy-prd:
        name: Terraform Deploy for prd
        if: github.ref == 'refs/heads/main' # Only run this job on the main branch
        runs-on: ubuntu-latest
        steps:
          - name: Terraform Apply
            run: terraform apply -auto-approve -var-file=envs/prd.tfvars
            working-directory: terraform
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            