name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger workflow for push to 'main' branch
  pull_request:
    branches:
      - main  # Trigger workflow for pull requests to 'main' branch

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.6  # Specify the Terraform version

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # Set your region here

      - name: Change direct
