name: Terraform Deploy to AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      # Step 3: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.4.0'

      # Step 4: Change to the directory where your Terraform files are located
      - name: Change to .terraform directory
        run: cd .terraform/

      # Step 5: Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: .terraform/

      # Step 6: Terraform Plan
      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -out=tfplan
          # Extract only the specific output values (e.g., instance public IP)
          INSTANCE_PUBLIC_IP=$(terraform output -raw instance_public_ip)
          echo "INSTANCE_PUBLIC_IP=$INSTANCE_PUBLIC_IP" >> $GITHUB_ENV  # Save as environment variable
        working-directory: .terraform/

      # Step 7: Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: .terraform/

      # Step 8: Save state to GITHUB_STATE (optional)
      - name: Save state to GITHUB_STATE
        run: echo "INSTANCE_PUBLIC_IP=${{ steps.plan.outputs.INSTANCE_PUBLIC_IP }}" >> $GITHUB_STATE
        working-directory: .terraform/

      # Step 9: Terraform Destroy (Clean Up) (optional)
      - name: Terraform Destroy (Clean Up)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: terraform destroy -auto-approve
        working-directory: .terraform/
